services:
  - type: web
    name: BE_LaptopGear
    env: docker
    plan: free
    branch: main
    buildCommand: "composer install --optimize-autoloader --no-dev && php artisan config:cache"
    startCommand: "php artisan serve --host=0.0.0.0 --port=10000"
    envVars:                 # Các biến môi trường Laravel cần
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: cdio4.internal
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: cdio4
      - key: DB_USERNAME
        value: root
      - key: DB_PASSWORD
        value:
